# A typical Rakefile

PORT  = 6283
HOSTS = 127.0.0.1
# 192.168.0.93:6333
actionset1:
	echo starting actionset1
	remote-ls
	remote-cat external_file

actionset2:
	echo starting actionset2
	remote-cal -m 4

actionset3:
	echo starting actionset3
	ls