# A typical Rakefile

PORT  = 65432
HOSTS = 127.0.0.1

actionset1:
	echo starting actionset1
	remote-cat external_file
		requires program.c program.h allfunctions.h
#actionset2:
#	echo starting actionset2
#	remote-cal -m 4

#actionset3:
#	echo starting actionset3
#	ls